// Distances and deadlines are tuned game approximations, not navigation advice.
export const routes = {
  oregon: { name: 'The Original Bad Idea', from: 'Independence, MO', to: 'Portland, OR', miles: 1900, days: 45, difficulty: 'HARD', blurb: 'Follow the old trail. Die of new expenses.', stops: [ ['Independence, MO','plains'], ['Lincoln, NE','plains'], ['North Platte, NE','plains'], ['Cheyenne, WY','mountains'], ['Rock Springs, WY','desert'], ['Twin Falls, ID','desert'], ['Boise, ID','mountains'], ['Bend, OR','mountains'], ['Portland, OR','city'] ] },
  la_ny: { name: 'Coast to Cope', from: 'Los Angeles, CA', to: 'New York, NY', miles: 2800, days: 61, difficulty: 'BRUTAL', blurb: 'Trade unaffordable sunshine for unaffordable square footage.', stops: [ ['Los Angeles, CA','city'], ['Barstow, CA','desert'], ['Flagstaff, AZ','desert'], ['Albuquerque, NM','desert'], ['Amarillo, TX','plains'], ['Oklahoma City, OK','plains'], ['St. Louis, MO','city'], ['Columbus, OH','plains'], ['Pittsburgh, PA','mountains'], ['New York, NY','city'] ] },
  tx_fl: { name: 'Humidity & Hostility', from: 'Austin, TX', to: 'Miami, FL', miles: 1350, days: 35, difficulty: 'HARD', blurb: 'Fuel, floods, and a state with a surprisingly aggressive wildlife department.', stops: [ ['Austin, TX','plains'], ['Houston, TX','city'], ['Lake Charles, LA','swamp'], ['New Orleans, LA','swamp'], ['Mobile, AL','coast'], ['Tallahassee, FL','swamp'], ['Orlando, FL','coast'], ['Miami, FL','coast'] ] },
  fl_wa: { name: 'The Great Moist Escape', from: 'Miami, FL', to: 'Seattle, WA', miles: 3300, days: 70, difficulty: 'BRUTAL', blurb: 'Escape the humidity. Arrive in rain. Pay for the privilege.', stops: [ ['Miami, FL','coast'], ['Orlando, FL','coast'], ['Atlanta, GA','city'], ['Nashville, TN','mountains'], ['St. Louis, MO','city'], ['Kansas City, MO','plains'], ['Sioux Falls, SD','plains'], ['Billings, MT','mountains'], ['Missoula, MT','mountains'], ['Spokane, WA','mountains'], ['Seattle, WA','city'] ] },
  nc_co: { name: 'Blackbeard’s Overdraft', from: 'Ocracoke Island, NC', to: 'Denver, CO', miles: 2100, days: 48, difficulty: 'HARD', blurb: 'Outer Banks pirate country to the Rockies. The plunder is gone. The overdraft fee survived.', stops: [ ['Ocracoke Island, NC','coast'], ['Hatteras Ferry, NC','coast'], ['Nags Head, NC','coast'], ['Raleigh, NC','city'], ['Asheville, NC','mountains'], ['Knoxville, TN','mountains'], ['Nashville, TN','city'], ['St. Louis, MO','city'], ['Kansas City, MO','plains'], ['Hays, KS','plains'], ['Denver, CO','mountains'] ] },
  ca_la: { name: 'From Gridlock to Gumbo', from: 'San Diego, CA', to: 'New Orleans, LA', miles: 1800, days: 43, difficulty: 'HARD', blurb: 'Desert heat to bayou steam. Your radiator has retained a lawyer.', stops: [ ['San Diego, CA','coast'], ['Yuma, AZ','desert'], ['Tucson, AZ','desert'], ['El Paso, TX','desert'], ['San Antonio, TX','plains'], ['Houston, TX','city'], ['Lafayette, LA','swamp'], ['New Orleans, LA','swamp'] ] },
};
export const biomes = { desert: { tile:0, name:'DESERT HIGHWAY', flavor:'The scenery is breathtaking. So is the temperature gauge.', hazard:'heat' }, coast: { tile:1, name:'COASTAL HIGHWAY', flavor:'Ocean views. Storm warnings. Waterfront prices.', hazard:'flood' }, plains: { tile:2, name:'THE GREAT PLAINS', flavor:'Nothing for miles. Somehow still a toll.', hazard:'storm' }, swamp: { tile:3, name:'BAYOU COUNTRY', flavor:'The mosquitoes have formed a homeowners association.', hazard:'gator' }, mountains: { tile:4, name:'MOUNTAIN PASS', flavor:'Thin air. Steep grades. A very confident GPS.', hazard:'snow' }, city: { tile:5, name:'URBAN SPRAWL', flavor:'Your destination is three miles and forty-five minutes away.', hazard:'parking' } };
export const getRoute = s => Object.hasOwn(routes,s?.route) ? routes[s.route] : routes.oregon;
export function getStop(s) { const route=getRoute(s); const index=Math.min(route.stops.length-1,Math.floor((s?.miles || 0)/route.miles*(route.stops.length-1))); return { index, name:route.stops[index][0], biome:route.stops[index][1] }; }
